### PR TITLE
macOS 10.12, Xcode 8 compatibility

### PR DESCRIPTION
**Pull request by firebolt55439**
Updated for macOS 10.12 (Sierra) compatibility. Also has length truncation with ellipsis for titles over 60 chars.

### CODE REVIEW

**Comment by firebolt55439** [comment]
Note that this also fixes a critical unrecognized selector bug I encountered when attempting to run the 2.0 version on my 2017 MB Pro.

**Comment by toddbluhm** [comment]
@firebolt55439 thank you so much for the contribution...but I am a little puzzled by it. I was under the impression cloudytabs no longer works because apple has been encrypting that info from safari.

Josh runs the official repo of cloudy tabs and here is the link to the apple encryption info I was talking about: https://github.com/josh-/CloudyTabs/issues/33

I have actually stopped using this program because the encryption prevents it from working for me.

I can still merge this in if you like, just wanted you to be aware that it will stop working eventually and maybe looking for an alternative solution might be better for you.

**Comment by firebolt55439** [comment]
That is rather strange certainly. I am on the latest software version for macOS, but the plist in question remains blissfully unencrypted for me. Do you have FileVault or some type of special encryption on perchance?

**Comment by toddbluhm** [comment]
My question would be, when was the last time you reformatted your mac? 

If you see my response at the end here: https://github.com/josh-/CloudyTabs/issues/37 I talk about how cloudytabs worked for me all the way up until I reformatted my mac. Then when safari re-downloaded all of that stuff, it came in the encrypted form :(

**Comment by firebolt55439** [comment]
It looks like the iOS 11 unfortunately brought iCloud tab encryption with it, for my Mac at least. However, there does appear to be a database file at `~/Library/Safari/CloudTabs.db` which remains unencrypted and has all the synced tabs, but I don’t know if Safari needs to be running in the background for the file to be updated. Maybe worth exploring.

**Comment by garyking** [comment]
@firebolt55439 The CloudTabs.db is a good lead. When I checked it, it was last updated about 2 minutes ago with the correct tabs from my iCloud Tabs. And I never open Safari. 

But since then (about 2 hours later), after some usage of Safari on my iPhone and opening and closing it several times, the file hasn't updated at all. So I'm not quite sure how to trigger it, without opening Safari.

For now, I wrote a script for myself to open Safari, wait 4 seconds, then close it, then access the SQLite database to get the tabs.

**Comment by josh-** [comment]
Thanks so much for this investigation @firebolt55439! I've just pushed a commit with the ability to use the `CloudTabs.db` file where available (whilst maintaining backwards compatibility with the `com.apple.Safari.plist` synced preference when it exists) - hoping to try and get it released today 👍

**Comment by firebolt55439** [comment]
No problem at all. I’m happy I could be of help. I love the app :)

**Comment by toddbluhm** [comment]
Just wanted to let everyone here know that the official CloudyTabs repo: https://github.com/josh-/CloudyTabs now has full compatibility with this fork. I am closing this fork as a result.

**Pull request closed without merging**
